name: voys_matrix_sliding_sync_example
description: Example app demonstrating voys_matrix_sliding_sync usage.
publish_to: 'none'

environment:
  sdk: ^3.10.4
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  matrix: ^4.1.0
  voys_matrix_sliding_sync:
    path: ../
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
